arrowParens: always
bracketSameLine: true
bracketSpacing: true
embeddedLanguageFormatting: auto
endOfLine: lf
printWidth: 80
proseWrap: always
quoteProps: consistent
semi: true
singleQuote: true
tabWidth: 4
trailingComma: all
useTabs: false
overrides:
  - files: '*.json'
    options:
      parser: 'json-stringify'
  - files:
      - '*.markdown'
      - '*.md'
      - '*.yaml'
      - '*.yml'
    options:
      tabWidth: 2
