[package]
name = "lambda-rust-docker"
description = "A sample repository for building Docker based AWS Lambda written in Rust."
version = "0.1.0"
edition = "2021"
authors = ["kv5h"]

[dependencies]
lambda_runtime = "0.11.2"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
